// Generated by Unloop
// Smart Washing Machine

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_start_clicked(|| {
        println!("start clicked");
    });
    
    app.on_pause_clicked(|| {
        println!("pause clicked");
    });
    
    app.on_stop_clicked(|| {
        println!("stop clicked");
    });
    

    
    app.run()
}
