// Generated Data Model

export struct AppData {
    remaining-time: float,
    load-weight: float,
    water-temp: float,
    machine-status: string,
    door-status: string,
    water-level-status: string,
    current-cycle: string,
    selected-cycle: string,
    water-temp-setting: string,
    spin-speed: string,
    extra-rinse: bool,
    auto-dispense: bool,
    delay-start: float,
    version: string,
}
